export type ProfileResponse = {
  id: number;
  uid: string;
  username: string;
  email: string;
  role: string;
  firstName: string;
  lastName: string;
  name: string;
  phone: string;
  country: string;
  state: string;
  city: string;
  address: string;
  affiliateId: number | null;
  hotelId: number | null;
  agentId: number | null;
  affiliatePartnerId: number | null;
  currentBalance: number;
  countryCode: string;
  markup: number;
  vendorId: number | null;
};
